name = "Rahulizer"
description = "Spell Rahul right!"
category = "lang"
visibility = "public"
status = "active"
is_primary = false

# Execution details
analysis_command = "python3 /app/analyze.py"
autofixer_command = ""
trigger = "code"
processors = ["source_code_load", "skip_cq"]

# Resource details
min_cpu_limit = 800
max_cpu_limit = 1500
min_memory_limit = 800
max_memory_limit = 2000
